// <auto-generated />
using Flashcard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flashcard.Migrations
{
    [DbContext(typeof(FlashcardDbContext))]
    [Migration("20260625193942_FirstSeedData")]
    partial class FirstSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flashcard.Models.HskLevel", b =>
                {
                    b.Property<int>("HskLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HskLevelId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HskLevelId");

                    b.ToTable("HskLevels");

                    b.HasData(
                        new
                        {
                            HskLevelId = 1,
                            Name = "HSK 1"
                        },
                        new
                        {
                            HskLevelId = 2,
                            Name = "HSK 2"
                        },
                        new
                        {
                            HskLevelId = 3,
                            Name = "HSK 3"
                        });
                });

            modelBuilder.Entity("Flashcard.Models.Word", b =>
                {
                    b.Property<int>("WordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordId"));

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HskLevelId")
                        .HasColumnType("int");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pinyin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WordId");

                    b.HasIndex("HskLevelId");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            WordId = 1,
                            Character = "爱",
                            HskLevelId = 1,
                            Meaning = "to love",
                            Pinyin = "ài"
                        },
                        new
                        {
                            WordId = 2,
                            Character = "八",
                            HskLevelId = 1,
                            Meaning = "eight",
                            Pinyin = "bā"
                        },
                        new
                        {
                            WordId = 3,
                            Character = "爸爸",
                            HskLevelId = 1,
                            Meaning = "father",
                            Pinyin = "bàba"
                        },
                        new
                        {
                            WordId = 4,
                            Character = "杯子",
                            HskLevelId = 1,
                            Meaning = "cup; glass; mug",
                            Pinyin = "bēizi"
                        },
                        new
                        {
                            WordId = 5,
                            Character = "北京",
                            HskLevelId = 1,
                            Meaning = "Beijing",
                            Pinyin = "běijīng"
                        },
                        new
                        {
                            WordId = 6,
                            Character = "本",
                            HskLevelId = 1,
                            Meaning = "measure word for books",
                            Pinyin = "běn"
                        },
                        new
                        {
                            WordId = 7,
                            Character = "不客气",
                            HskLevelId = 1,
                            Meaning = "you're welcome",
                            Pinyin = "búkèqi"
                        },
                        new
                        {
                            WordId = 8,
                            Character = "不",
                            HskLevelId = 1,
                            Meaning = "not; no",
                            Pinyin = "bù"
                        },
                        new
                        {
                            WordId = 9,
                            Character = "菜",
                            HskLevelId = 1,
                            Meaning = "vegetable; dish",
                            Pinyin = "cài"
                        },
                        new
                        {
                            WordId = 10,
                            Character = "茶",
                            HskLevelId = 1,
                            Meaning = "tea",
                            Pinyin = "chá"
                        },
                        new
                        {
                            WordId = 11,
                            Character = "吧",
                            HskLevelId = 2,
                            Meaning = "[particle making suggestion, e.g. 'let’s…']",
                            Pinyin = "ba"
                        },
                        new
                        {
                            WordId = 12,
                            Character = "白",
                            HskLevelId = 2,
                            Meaning = "white",
                            Pinyin = "bái"
                        },
                        new
                        {
                            WordId = 13,
                            Character = "百",
                            HskLevelId = 2,
                            Meaning = "hundred",
                            Pinyin = "bǎi"
                        },
                        new
                        {
                            WordId = 14,
                            Character = "帮助",
                            HskLevelId = 2,
                            Meaning = "to help",
                            Pinyin = "bāngzhù"
                        },
                        new
                        {
                            WordId = 15,
                            Character = "报纸",
                            HskLevelId = 2,
                            Meaning = "newspaper",
                            Pinyin = "bàozhǐ"
                        },
                        new
                        {
                            WordId = 16,
                            Character = "比",
                            HskLevelId = 2,
                            Meaning = "to compare",
                            Pinyin = "bǐ"
                        },
                        new
                        {
                            WordId = 17,
                            Character = "别",
                            HskLevelId = 2,
                            Meaning = "don’t; other; separate",
                            Pinyin = "bié"
                        },
                        new
                        {
                            WordId = 18,
                            Character = "宾馆",
                            HskLevelId = 2,
                            Meaning = "guesthouse; hotel",
                            Pinyin = "bīnguǎn"
                        },
                        new
                        {
                            WordId = 19,
                            Character = "长",
                            HskLevelId = 2,
                            Meaning = "long",
                            Pinyin = "cháng"
                        },
                        new
                        {
                            WordId = 20,
                            Character = "唱歌",
                            HskLevelId = 2,
                            Meaning = "to sing; singing",
                            Pinyin = "chànggē"
                        },
                        new
                        {
                            WordId = 21,
                            Character = "阿姨",
                            HskLevelId = 3,
                            Meaning = "auntie [mother's younger sister]",
                            Pinyin = "āyí"
                        },
                        new
                        {
                            WordId = 22,
                            Character = "啊",
                            HskLevelId = 3,
                            Meaning = "ah",
                            Pinyin = "a"
                        },
                        new
                        {
                            WordId = 23,
                            Character = "矮",
                            HskLevelId = 3,
                            Meaning = "short (height)",
                            Pinyin = "ǎi"
                        },
                        new
                        {
                            WordId = 24,
                            Character = "爱好",
                            HskLevelId = 3,
                            Meaning = "interests; hobbies",
                            Pinyin = "àihào"
                        },
                        new
                        {
                            WordId = 25,
                            Character = "安静",
                            HskLevelId = 3,
                            Meaning = "to be quiet",
                            Pinyin = "ānjìng"
                        },
                        new
                        {
                            WordId = 26,
                            Character = "把",
                            HskLevelId = 3,
                            Meaning = "grasp; measure word for knives",
                            Pinyin = "bǎ"
                        },
                        new
                        {
                            WordId = 27,
                            Character = "搬",
                            HskLevelId = 3,
                            Meaning = "to move",
                            Pinyin = "bān"
                        },
                        new
                        {
                            WordId = 28,
                            Character = "班",
                            HskLevelId = 3,
                            Meaning = "class",
                            Pinyin = "bān"
                        },
                        new
                        {
                            WordId = 29,
                            Character = "半",
                            HskLevelId = 3,
                            Meaning = "half",
                            Pinyin = "bàn"
                        },
                        new
                        {
                            WordId = 30,
                            Character = "办法",
                            HskLevelId = 3,
                            Meaning = "way; method; solution",
                            Pinyin = "bànfǎ"
                        });
                });

            modelBuilder.Entity("Flashcard.Models.Word", b =>
                {
                    b.HasOne("Flashcard.Models.HskLevel", "HskLevel")
                        .WithMany("Words")
                        .HasForeignKey("HskLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HskLevel");
                });

            modelBuilder.Entity("Flashcard.Models.HskLevel", b =>
                {
                    b.Navigation("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
